#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE sets $KEY and upserts KEY=VALUE into ENV_FILE (creates
# it; replaces any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  printf -v "$key" '%s' "$value"
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Tencent payer billing setup for Keel (#29) and the admin/member question (#9).
#
#   scripts/wizards/tencent-payer-billing.sh
#
# Run from anywhere inside the repo, with tccli signed in as the payer account
# (TCCLI_PROFILE=<name> picks a tccli profile). The wizard never asks for an
# access key. It keeps its answers in .keel/ (git-ignored), so a re-run resumes
# where it stopped and offers to skip stages already done.
#
# scripts/wizards/test-tencent-payer-billing.sh runs it end to end against a
# stubbed tccli.

cd "$(git rev-parse --show-toplevel)"
mkdir -p .keel
ENV_FILE=.keel/payer-billing.env
ANSWERS=.keel/payer-answers.env
TOTAL_STAGES=8

load_file() {
  local line k
  [[ -f "$1" ]] || return 0
  while IFS= read -r line; do
    k=${line%%=*}
    if [[ "$k" =~ ^[A-Z][A-Za-z0-9_]*$ ]]; then printf -v "$k" '%s' "${line#*=}"; fi
  done < "$1"
}
load_file "$ENV_FILE"
load_file "$ANSWERS"

# ask_or KEY "Prompt" DEFAULT [optional] is ask, falling back to DEFAULT on an
# empty answer. Without "optional" it insists on a value.
ask_or() {
  local key="$1" prompt="$2" def="$3" tries=0
  [[ -n "$def" ]] && prompt="$prompt ${DIM}[default: $def]${RESET}"
  while :; do
    ask "$key" "$prompt"
    [[ -z "${!key}" ]] && printf -v "$key" '%s' "$def"
    [[ -n "${!key}" || "${4:-}" == optional ]] && break
    (( ++tries < 3 )) || fail "$key is required"
    warn "a value is required"
  done
  write_env "$key" "${!key}"
}

record() { ENV_FILE="$ANSWERS" write_env "$1" "$2"; }

# already ID: true when stage ID finished on an earlier run and should be skipped.
already() {
  local done_key="DONE_$1"
  [[ "${!done_key:-}" == yes ]] || return 1
  note "Done on a previous run."
  ! confirm "Redo this stage?"
}
mark_done() { write_env "DONE_$1" yes; }

TC_ARGS=()
[[ -n "${TCCLI_PROFILE:-}" ]] && TC_ARGS=(--profile "$TCCLI_PROFILE")
tc() { tccli "$@" ${TC_ARGS[@]+"${TC_ARGS[@]}"}; }
# tcq FILTER ARGS... prints one JMESPath-filtered value without JSON quotes.
# On failure it shows tccli's error and returns tccli's status.
tcq() {
  local f="$1" out err st=0
  shift
  err=$(mktemp)
  out=$(tc "$@" --filter "$f" 2>"$err") || st=$?
  if (( st )); then
    warn "tccli $1 $2 failed:" >&2
    sed 's/^/      /' "$err" >&2
  fi
  rm -f "$err"
  (( st == 0 )) || return "$st"
  printf '%s' "$out" | tr -d '"[:space:]'
}

show_cmd() { printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"; }
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; exit 1; }

ROLE_ARN_RE='^qcs::cam::uin/([0-9]+):roleName/([A-Za-z0-9_+=,.@-]+)$'
ROLE_NAME_RE='^[A-Za-z0-9_+=,.@-]{1,128}$'

prev_month() {
  local y m
  y=$(date +%Y); m=$((10#$(date +%m) - 1))
  (( m == 0 )) && { m=12; y=$((y - 1)); }
  printf '%04d-%02d' "$y" "$m"
}

# summarize FILE STATUS prints "ok: <list>=<n> ..." or "error: <code>".
summarize() {
  if [[ "$2" != 0 ]]; then
    printf 'error: %s' "$(grep -oE 'code: ?[A-Za-z.]+' "$1" | head -n1 | sed 's/code: *//' || true)"
    return
  fi
  python3 - "$1" <<'PY' 2>/dev/null || printf 'ok (see %s)' "$1"
import json, sys
d = json.load(open(sys.argv[1]))
parts = [f"{k}={len(v)}" for k, v in d.items() if isinstance(v, list)]
parts += [f"{k}={v}" for k, v in d.items() if k in ("Total", "Ready") or v is None]
costs = [float(i.get("RealTotalCost") or 0) for v in d.values() if isinstance(v, list) for i in v if isinstance(i, dict)]
if costs:
    parts.append(f"RealTotalCost={sum(costs):.2f}")
print("ok: " + (" ".join(parts) or "no list fields"), end="")
PY
}

# trusted_principals ROLE prints the qcs principals the role's trust policy
# lets call sts:AssumeRole, one per line.
trusted_principals() {
  tc cam GetRole --RoleName "$1" --region "$KEEL_TENCENT_REGION" --filter RoleInfo.PolicyDocument \
    | python3 -c '
import json, sys
doc = json.loads(json.loads(sys.stdin.read()))
for s in doc.get("statement", []):
    acts = s.get("action", [])
    acts = [acts] if isinstance(acts, str) else acts
    if s.get("effect") == "allow" and "name/sts:AssumeRole" in acts:
        qcs = s.get("principal", {}).get("qcs", [])
        print("\n".join([qcs] if isinstance(qcs, str) else qcs))
'
}

banner "Tencent payer billing for Keel (#29, #9)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Sign in as the payer"
if ! already preflight; then
  say "Every step runs in the payer account, the only account that sees the"
  say "organisation's bills. tccli must already be signed in there; this wizard"
  say "never asks for or stores an access key."
  command -v tccli >/dev/null || fail "tccli is missing: brew install tccli (or pip install tccli)"
  command -v python3 >/dev/null || fail "python3 is missing: the wizard reads tccli's JSON with it"
  ask_or KEEL_TENCENT_PAYER_UIN "Payer UIN:" "${KEEL_TENCENT_PAYER_UIN:-200045645249}"
  ask_or KEEL_TENCENT_REGION "Region for the bill bucket and billing API:" "${KEEL_TENCENT_REGION:-ap-bangkok}"
  show_cmd "tccli sts GetCallerIdentity"
  caller=$(tcq AccountId sts GetCallerIdentity --region "$KEEL_TENCENT_REGION" || true)
  if [[ "$caller" != "$KEEL_TENCENT_PAYER_UIN" ]]; then
    warn "tccli is signed in as '${caller:-nothing}', not the payer $KEEL_TENCENT_PAYER_UIN."
    say "Switch profile (TCCLI_PROFILE=<name>) or use Tencent Cloud Shell in the payer account, then re-run."
    exit 1
  fi
  TENCENT_APPID=$(tcq AppId cam GetUserAppId --region "$KEEL_TENCENT_REGION" || true)
  [[ -n "$TENCENT_APPID" ]] || fail "cam GetUserAppId returned nothing"
  write_env TENCENT_APPID "$TENCENT_APPID"
  say "${GREEN}✓${RESET} signed in as payer $caller (APPID $TENCENT_APPID)"
  mark_done preflight
  pause
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Keel's base identity and the billing role"
if ! already identity; then
  say "Keel signs its Tencent calls with one keyless base identity, tencent.Credentials():"
  say "TKE pod identity (the role in keel-api's ServiceAccount annotation), else the CVM role."
  say "Bill sync assumes a separate payer role, KEEL_TENCENT_BILL_ROLE, from that base"
  say "identity with STS AssumeRole, so only bill sync ever holds payer billing access."
  ask_or KEEL_IDENTITY_KIND "How does Keel run: tke (pod identity) or cvm (instance role)?" "${KEEL_IDENTITY_KIND:-tke}"
  det_role=""
  if [[ "$KEEL_IDENTITY_KIND" == tke ]]; then
    ask_or KEEL_K8S_NAMESPACE "Keel's namespace:" "${KEEL_K8S_NAMESPACE:-keel}"
    ask_or KEEL_K8S_SA "keel-api's ServiceAccount:" "${KEEL_K8S_SA:-keel-api}"
    if command -v kubectl >/dev/null && confirm "Read the ServiceAccount's role-arn annotation with kubectl get (read-only)?"; then
      det_role=$(kubectl -n "$KEEL_K8S_NAMESPACE" get sa "$KEEL_K8S_SA" -o jsonpath='{.metadata.annotations.tke\.cloud\.tencent\.com/role-arn}' 2>/dev/null || true)
      note "role-arn annotation: ${det_role:-none}"
    fi
  else
    say "CVM console → Keel's instance → Instance settings shows the bound role; its ARN is"
    say "qcs::cam::uin/<the CVM's UIN>:roleName/<role name>."
  fi
  ask_or KEEL_BASE_ROLE_ARN "Keel's base role ARN:" "${det_role:-${KEEL_BASE_ROLE_ARN:-}}"
  [[ "$KEEL_BASE_ROLE_ARN" =~ $ROLE_ARN_RE ]] ||
    fail "'$KEEL_BASE_ROLE_ARN' is not a role ARN like qcs::cam::uin/<uin>:roleName/<name>; re-run this stage"
  ask_or KEEL_TENCENT_BILL_ROLE "Name of the payer role bill sync will assume:" "${KEEL_TENCENT_BILL_ROLE:-KeelBillReader}"
  [[ "$KEEL_TENCENT_BILL_ROLE" =~ $ROLE_NAME_RE ]] ||
    fail "'$KEEL_TENCENT_BILL_ROLE' is not a CAM role name (letters, digits, _+=,.@-); re-run this stage"
  [[ "$KEEL_BASE_ROLE_ARN" != "qcs::cam::uin/$KEEL_TENCENT_PAYER_UIN:roleName/$KEEL_TENCENT_BILL_ROLE" ]] ||
    fail "the billing role must not be Keel's base role; pick another name and re-run this stage"
  mark_done identity
  pause
fi
KEEL_BILL_ROLE_ARN="qcs::cam::uin/$KEEL_TENCENT_PAYER_UIN:roleName/$KEEL_TENCENT_BILL_ROLE"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "COS bucket for the bills"
if ! already bucket; then
  say "Bill Storage writes into a private COS bucket in the payer account."
  ask_or BUCKET_SHORT "Bucket name without the APPID suffix:" "${BUCKET_SHORT:-keel-bills}"
  write_env KEEL_TENCENT_BILL_BUCKET "$BUCKET_SHORT-$TENCENT_APPID"
  endpoint="https://$KEEL_TENCENT_BILL_BUCKET.cos.$KEEL_TENCENT_REGION.myqcloud.com/"
  code=$(curl -s -o /dev/null -w '%{http_code}' "$endpoint" || true)
  if [[ "$code" != 403 ]]; then
    open_url "https://console.tencentcloud.com/cos/bucket"
    step "Create Bucket → Region: $KEEL_TENCENT_REGION, Name: $BUCKET_SHORT"
    step "Access permissions: Private read/write. Leave versioning and encryption as you prefer."
    pause "Press Enter once the bucket exists."
    code=$(curl -s -o /dev/null -w '%{http_code}' "$endpoint" || true)
  fi
  case "$code" in
    403) say "${GREEN}✓${RESET} $KEEL_TENCENT_BILL_BUCKET exists in $KEEL_TENCENT_REGION and is private" ;;
    200) fail "the bucket answers anonymous requests: make it private before continuing" ;;
    *)   fail "$endpoint returned HTTP $code: wrong name or region? Re-run this stage." ;;
  esac
  mark_done bucket
  pause
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Bill Storage delivery to COS"
if ! already delivery; then
  open_url "https://console.tencentcloud.com/expense/bill/overview"
  step "Billing Center → Bill Overview (Bill Management → Saving Bills to COS) → enable Bill Storage."
  step "In the pop-up click Authorize, then Grant (creates the service role that writes to COS)."
  step "File types: subscribe only the Standard bill (FOCUS) under Keel's prefix."
  warn "Do not subscribe the Cost Allocation Bill (FOCUS) or any other bill type under that prefix."
  step "Bucket: $KEEL_TENCENT_BILL_BUCKET ($KEEL_TENCENT_REGION)."
  step "Tick 'Automatic Account Synchronization' and select every member account."
  step "Tick 'Synchronize historical monthly bills' (18 months, arrives the next day)."
  note "Daily files arrive 03:00–22:00 on Day+1. If the bucket is not offered, its region may not be"
  note "supported by Bill Storage (UNVERIFIED which regions are); recreate it where it is offered."
  if confirm "Is Bill Storage enabled with those settings?"; then
    write_env BILL_STORAGE_ENABLED_ON "$(date +%F)"
    mark_done delivery
  else
    SKIPPED+=("Bill Storage delivery (stage 4)")
  fi
  pause
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Read-only billing role in the payer"
if ! already role; then
  cat > .keel/trust.json <<EOF
{"version":"2.0","statement":[{"action":"name/sts:AssumeRole","effect":"allow","principal":{"qcs":["$KEEL_BASE_ROLE_ARN"]}}]}
EOF
  cat > .keel/cos-read.json <<EOF
{"version":"2.0","statement":[
 {"effect":"allow","action":["name/cos:GetBucket","name/cos:HeadBucket"],
  "resource":["qcs::cos:$KEEL_TENCENT_REGION:uid/$TENCENT_APPID:$KEEL_TENCENT_BILL_BUCKET/"]},
 {"effect":"allow","action":["name/cos:GetObject","name/cos:HeadObject"],
  "resource":["qcs::cos:$KEEL_TENCENT_REGION:uid/$TENCENT_APPID:$KEEL_TENCENT_BILL_BUCKET/*"]}]}
EOF
  say "Role $KEEL_TENCENT_BILL_ROLE gets:"
  step "trust: .keel/trust.json (only Keel's base role $KEEL_BASE_ROLE_ARN may assume it)"
  step "KeelBillBucketRead: .keel/cos-read.json (list + read the bill bucket, nothing else)"
  step "QcloudFinanceBillReadOnlyAccess: preset; covers DescribeBill* incl. DescribeBillSummaryByPayMode,"
  note "  which Keel calls for invoice reconciliation. The narrower custom action is"
  note "  name/finance:DescribeBillSummaryByPayMode (UNVERIFIED: docs show only finance:DescribeBill*)."
  if confirm "Create or update the role and policies with tccli now?"; then
    r=(--region "$KEEL_TENCENT_REGION")
    if [[ -n "$(tcq RoleInfo.RoleId cam GetRole --RoleName "$KEEL_TENCENT_BILL_ROLE" "${r[@]}" 2>/dev/null || true)" ]]; then
      note "role exists"
      if confirm "Replace its trust policy with .keel/trust.json?"; then
        tc cam UpdateAssumeRolePolicy --RoleName "$KEEL_TENCENT_BILL_ROLE" --PolicyDocument "$(cat .keel/trust.json)" "${r[@]}" >/dev/null
      fi
    else
      tc cam CreateRole --RoleName "$KEEL_TENCENT_BILL_ROLE" --PolicyDocument "$(cat .keel/trust.json)" \
        --Description "Keel: read payer bills (#29)" --SessionDuration 3600 "${r[@]}" >/dev/null
    fi
    pid=$(tcq "List[?PolicyName=='KeelBillBucketRead'].PolicyId|[0]" cam ListPolicies --Scope Local --Keyword KeelBillBucketRead "${r[@]}")
    if [[ -z "$pid" || "$pid" == null ]]; then
      pid=$(tcq PolicyId cam CreatePolicy --PolicyName KeelBillBucketRead --PolicyDocument "$(cat .keel/cos-read.json)" \
        --Description "Keel: list and read $KEEL_TENCENT_BILL_BUCKET" "${r[@]}")
    else
      tc cam UpdatePolicy --PolicyId "$pid" --PolicyDocument "$(cat .keel/cos-read.json)" "${r[@]}" >/dev/null
    fi
    attached=$(tc cam ListAttachedRolePolicies --RoleName "$KEEL_TENCENT_BILL_ROLE" --Page 1 --Rp 200 "${r[@]}" --filter "List[].PolicyName")
    grep -q '"KeelBillBucketRead"' <<<"$attached" || tc cam AttachRolePolicy --AttachRoleName "$KEEL_TENCENT_BILL_ROLE" --PolicyId "$pid" "${r[@]}" >/dev/null
    grep -q '"QcloudFinanceBillReadOnlyAccess"' <<<"$attached" || tc cam AttachRolePolicy --AttachRoleName "$KEEL_TENCENT_BILL_ROLE" --PolicyName QcloudFinanceBillReadOnlyAccess "${r[@]}" >/dev/null
  else
    open_url "https://console.tencentcloud.com/cam/role"
    say "Create the role and policies above in the CAM console, then press Enter."
    pause
  fi
  show_cmd "tccli cam GetRole --RoleName $KEEL_TENCENT_BILL_ROLE"
  principals=$(trusted_principals "$KEEL_TENCENT_BILL_ROLE" || true)
  if [[ "$principals" == "$KEEL_BASE_ROLE_ARN" ]]; then
    say "${GREEN}✓${RESET} trust allows sts:AssumeRole from $KEEL_BASE_ROLE_ARN only"
  else
    fail "the trust policy's AssumeRole principals are '${principals//$'\n'/, }', want exactly $KEEL_BASE_ROLE_ARN"
  fi
  show_cmd "tccli cam ListAttachedRolePolicies --RoleName $KEEL_TENCENT_BILL_ROLE --Page 1 --Rp 200"
  attached=$(tc cam ListAttachedRolePolicies --RoleName "$KEEL_TENCENT_BILL_ROLE" --Page 1 --Rp 200 --region "$KEEL_TENCENT_REGION" --filter "List[].PolicyName" || true)
  ok=1
  for p in KeelBillBucketRead QcloudFinanceBillReadOnlyAccess; do
    if grep -q "\"$p\"" <<<"$attached"; then say "${GREEN}✓${RESET} $p attached"; else warn "$p not attached"; ok=0; fi
  done
  (( ok )) || fail "fix the role, then re-run this stage"

  cat > .keel/base-assume.json <<EOF
{"version":"2.0","statement":[{"effect":"allow","action":["name/sts:AssumeRole"],"resource":["$KEEL_BILL_ROLE_ARN"]}]}
EOF
  say ""
  say "Keel's base role also needs permission to assume it. In the account that owns"
  say "$KEEL_BASE_ROLE_ARN, attach this policy to that role:"
  step ".keel/base-assume.json: sts:AssumeRole on $KEEL_BILL_ROLE_ARN"
  open_url "https://console.tencentcloud.com/cam/policy"
  pause "Press Enter once it is attached."

  if confirm "Will Keel mirror Budgets to Tencent (KEEL_TENCENT_BUDGETS=1, #39)?"; then
    write_env KEEL_TENCENT_BUDGETS 1
    cat > .keel/base-budgets.json <<EOF
{"version":"2.0","statement":[{"effect":"allow","action":["name/billing:CreateBudget","name/billing:ModifyBudget","name/billing:DeleteBudget","name/billing:DescribeBudget"],"resource":["*"]}]}
EOF
    warn "Budgets do not use $KEEL_TENCENT_BILL_ROLE: Keel calls them as its base identity."
    warn "Attach .keel/base-budgets.json to Keel's base role, not to the billing role."
    note "UNVERIFIED: the budget actions' namespace (billing: or finance:); the CAM visual editor shows the right one."
    pause "Press Enter once the base role has them."
  else
    write_env KEEL_TENCENT_BUDGETS 0
  fi
  mark_done role
  pause
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "#9: who calls the *ForOrganization APIs?"
if ! already q9; then
  say "The CN docs say a member calls DescribeBillDetailForOrganization to read bills the"
  say "admin paid for it; the international docs say the reverse. This probe calls the"
  say "APIs as the payer and as a member, keylessly: the member call assumes the org's"
  say "access role in that member with your payer session."
  ENV_FILE="$ANSWERS" ask_or Q9_MEMBER_UIN "A member UIN whose bills the payer pays:" "${Q9_MEMBER_UIN:-}"
  ENV_FILE="$ANSWERS" ask_or Q9_MEMBER_ROLE "Role the payer can assume in that member:" "${Q9_MEMBER_ROLE:-OrganizationAccessControlRole}"
  ENV_FILE="$ANSWERS" ask_or Q9_PROBE_MONTH "Bill month to probe (YYYY-MM, one with admin-paid charges):" "$(prev_month)"
  month=$Q9_PROBE_MONTH
  member_arn="qcs::cam::uin/$Q9_MEMBER_UIN:roleName/$Q9_MEMBER_ROLE"
  for who in admin member; do
    as=()
    [[ "$who" == member ]] && as=(--role-arn "$member_arn" --role-session-name keel-q9)
    for api in DescribeBillDetailForOrganization DescribeBillSummaryForOrganization DescribeBillSummaryByPayMode; do
      case "$api" in
        DescribeBillDetailForOrganization)  args=(--Month "$month" --Offset 0 --Limit 1 --NeedRecordNum 1) ;;
        DescribeBillSummaryForOrganization) args=(--Month "$month" --GroupType payMode) ;;
        DescribeBillSummaryByPayMode)       args=(--BeginTime "$month" --EndTime "$month") ;;
      esac
      show_cmd "tccli billing $api ${args[*]} ${as[*]:-}"
      out=".keel/probe-$who-$api.json"
      set +e; tc billing "$api" "${args[@]}" ${as[@]+"${as[@]}"} --region "$KEEL_TENCENT_REGION" >"$out" 2>&1; st=$?; set -e
      printf -v "RES_${who}_$api" '%s' "$(summarize "$out" "$st")"
      v="RES_${who}_$api"; note "  → ${!v}"
    done
  done
  for api in DescribeBillDetailForOrganization DescribeBillSummaryForOrganization DescribeBillSummaryByPayMode; do
    a="RES_admin_$api" m="RES_member_$api"
    record "Q9_ADMIN_$api" "${!a}"
    record "Q9_MEMBER_$api" "${!m}"
  done
  has_data() { [[ "$1" == ok:* && "$1" != *DetailSet=0* ]]; }
  a=${RES_admin_DescribeBillDetailForOrganization:-} m=${RES_member_DescribeBillDetailForOrganization:-}
  guess="unclear"
  if has_data "$m" && ! has_data "$a"; then guess="member"
  elif has_data "$a" && ! has_data "$m"; then guess="admin"
  elif has_data "$a" && has_data "$m"; then guess="both"
  fi
  say ""
  say "Raw responses: .keel/probe-*.json. From the detail call, the caller looks like: ${BOLD}$guess${RESET}"
  ENV_FILE="$ANSWERS" ask_or Q9_FOR_ORGANIZATION_CALLER "Your conclusion (admin | member | both | neither):" "$guess"
  ENV_FILE="$ANSWERS" ask Q9_NOTE "Anything to add for #9 (one line, Enter to skip):"
  record Q9_PROBED_ON "$(date +%F)"
  record Q9_NOTE "${Q9_NOTE:-}"
  comment=".keel/q9-comment.md"
  # shellcheck disable=SC2016 # backticks are Markdown, not command substitution
  {
    printf 'Probe from `scripts/wizards/tencent-payer-billing.sh`, %s, bill month %s.\n\n' "$(date +%F)" "$month"
    printf '| API | as payer %s | as member %s |\n|---|---|---|\n' "$KEEL_TENCENT_PAYER_UIN" "$Q9_MEMBER_UIN"
    for api in DescribeBillDetailForOrganization DescribeBillSummaryForOrganization DescribeBillSummaryByPayMode; do
      a="RES_admin_$api" m="RES_member_$api"
      printf '| `%s` | %s | %s |\n' "$api" "${!a}" "${!m}"
    done
    printf '\n**`*ForOrganization` caller: %s.** %s\n' "$Q9_FOR_ORGANIZATION_CALLER" "${Q9_NOTE:-}"
  } > "$comment"
  say "${GREEN}✓${RESET} answers in $ANSWERS; ready-to-paste comment in $comment"
  if command -v gh >/dev/null && confirm "Post $comment to issue #9 now with gh?"; then
    gh issue comment 9 -R hx-thanadej/keel --body-file "$comment"
  fi
  mark_done q9
  pause
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "First delivery: prefix and file mode"
if ! already layout; then
  say "Bill Storage was enabled on ${BILL_STORAGE_ENABLED_ON:-an unknown date}. Daily files land on Day+1,"
  say "and you need two consecutive daily Standard bill (FOCUS) files for this stage."
  open_url "https://console.tencentcloud.com/cos/bucket?bucket=$KEEL_TENCENT_BILL_BUCKET&region=$KEEL_TENCENT_REGION"
  if ! confirm "Are at least two daily Standard bill (FOCUS) files in the bucket?"; then
    SKIPPED+=("stages 7–8: re-run this wizard once two daily FOCUS files have arrived")
    finish
    exit 0
  fi
  say "Keel ingests every .csv/.csv.gz/.gz/.zip/.parquet under its prefix as a FOCUS bill."
  warn "The prefix must hold only Standard bill (FOCUS) files, or cost allocation and"
  warn "non-FOCUS files are parsed as bills and counted twice."
  ask_or KEEL_TENCENT_BILL_PREFIX "Prefix (folder path) that holds only Standard bill (FOCUS) files:" "${KEEL_TENCENT_BILL_PREFIX:-}" optional
  if confirm "Does that prefix also hold monthly FOCUS files or any other bill type?"; then
    record BILL_PREFIX_ISOLATES_STANDARD_FOCUS no
    warn "Keel needs a filename filter before it can read this layout; note it on #29."
  else
    record BILL_PREFIX_ISOLATES_STANDARD_FOCUS yes
  fi
  say "Tencent documents the daily FOCUS file as month-to-date, so day 2's file repeats day 1's lines."
  say "Daily delivery therefore defaults to cumulative. Answer N to keep it."
  note "Answer y only for one-file-per-day deliveries, where day 2's file holds just day 2's lines (per-day)."
  if confirm "Does each daily file hold only that day's lines (one file per day)?"; then mode=per-day; else mode=cumulative; fi
  write_env KEEL_TENCENT_BILL_MODE "$mode"
  record BILL_FILE_MODE "$mode"
  mark_done layout
  pause
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Configure Keel and check the first sync"
say "Set these on keel-api (Deployment env):"
printf '\n'
for k in KEEL_TENCENT_BILL_BUCKET KEEL_TENCENT_BILL_PREFIX KEEL_TENCENT_PAYER_UIN KEEL_TENCENT_REGION \
  KEEL_TENCENT_BILL_MODE KEEL_TENCENT_BILL_ROLE KEEL_TENCENT_BUDGETS; do
  printf '    %s=%s\n' "$k" "${!k}"
done
printf '\n'
note "keel-api keeps its base role ($KEEL_BASE_ROLE_ARN); do not change its ServiceAccount"
note "or CVM role. Bill sync assumes $KEEL_BILL_ROLE_ARN from it."
if [[ "$KEEL_TENCENT_BUDGETS" == 1 ]]; then
  note "Budgets run as the base role, so .keel/base-budgets.json belongs on that role."
fi
pause "Press Enter once Keel is redeployed with these values."
say "Bill sync runs at start-up and hourly. Look for 'tencent bill sync' with new_files > 0, and no 'ALERT':"
show_cmd "kubectl -n ${KEEL_K8S_NAMESPACE:-keel} logs deploy/keel-api | grep 'tencent bill'"
if command -v kubectl >/dev/null && [[ "$KEEL_IDENTITY_KIND" == tke ]] && confirm "Run that now?"; then
  kubectl -n "$KEEL_K8S_NAMESPACE" logs deploy/keel-api 2>/dev/null | grep 'tencent bill' | tail -n 5 || warn "no bill sync lines yet"
fi
if confirm "Did Keel list and load bill files with no ALERT, and does GET /v1/tenants/{home}/cost-loads show reconcile_status ok?"; then
  record KEEL_LISTS_BILLS_KEYLESS yes
  note "#29's first criterion is met. Close #29 once daily files keep arriving, and #9 after the comment is posted."
else
  record KEEL_LISTS_BILLS_KEYLESS no
  SKIPPED+=("Keel bill sync not confirmed: check the role trust and base-role grant (stage 5) and the env above")
fi
pause

finish
